### ISSUE TITLE
Preprocessors are not parsed correctly

### ISSUE THREAD

**Issue by Belluxx** [Xavier-Maruff/zed-fortran#2]
Preprocessors are not parsed correctly: `#if defined VAR` for example is rendered as white text except for `in` that is yellow.

The same happens if `#define VAR` is written at the start of the code, the text is pure white except for the `in` of `define` that is highlighted separately.

**Comment by Xavier-Maruff** [comment]
Hi, thanks for your interest! This extension currently doesn't support syntax highlighting for C preprocessor/FPP directives/FYPP, only Fortran proper. I'm not opposed to the idea at all though, if you want to submit a PR I'll merge it :)
